language: scala
scala:
- 2.10.4
jdk:
- openjdk6

before_script: ./scripts/prepublish.sh
script: ./scripts/ci-build.sh

env:
  global:
  - BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
  - secure: fse8HJTdcP9wp7mmO2QywSvtf9upPfkgYrMfPc6OTxNy0JhHdBLICbt01ZJv/hBJJU56pYt0Z6rxCkSC4ykeuH5IdBp5PUnuK5q+XxUvj/9u+5VLwGe3ft6ZYb5c4o3dZJWt5tbgarp1A1hpREp3qZN8xf0Kn4973MppmaZ5cmM=
  - secure: JTE/6ObbZkn5odN/inMe4PMRb766J8lWty1o8xujSCC/vHlEgQ4xWQAUUQz7Qvimk8XjKUOh7F80kScuj2aLMoZIZWjsxYEEsdWgrGoLWa0euxUBPLEJhFO6VLJFQ66CQYiL2eizP1ld0ppP8KCmQqR/iLx/P/aunbPh0c3BF84=
  - secure: Y2xISC+kbsPY6vut5JS/JRdqo3KT9BAUcPPngrkOguFl+tariactrKENxxfOUBdDfXXZpLsjFl4q9Sc1ciPsnnus9eujrxM7k0gbjh3EGaO1hGyyf1uPc3zg/uBzQ11Uuv6ssawC/xnjXlQN0H1WO517FLxKHDbEc3YXY1Xsg18=
