language: scala
scala:
- 2.10.4
jdk:
- openjdk6

before_script: ./scripts/prepublish.sh
script: ./scripts/ci-build.sh

env:
  global:
  - BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
  - secure: Rmx0EtLLgwjHdRWpjfzw7oSZ9/yiBv2x+hLnus6xr5qB5NMdmsBn+695AKO6EKcTMuWhJAYtZjUNJ47PENwEiZnbL+2FsIwzB9W6FOn2B5owMG0IwCqMG8S9cELxBsm6eaWnNhwuzDjsQ82ydhCfYZoc+ZI8lzTdqU64SjoZtFM=
  - secure: ZA/lbF0O8olQliTY9KdsDcqb+gBGsQAdg4dbQ/ICu2tKHf28/cv3gyjLISGtGzRtwWABd25LsTyUejmuMcCEyHGWUSc6Jd0ZZI96J/TvVZmVixr0DRQCVRJNSv3B336Xja5NJXBcyTQ2Xi1jAQpF2+HC+wdGItUzcocFB3nBjfA=
  - secure: i5+kimfraeBsbg0EMGT5BD5xqsRBx7D/ELqGXES4OOKHgqJ+Bra9DjlmjYeRrrlbqpBT6ARMuTluE+8nGlT99vE5oJ69DPTJ1MHWr3UFH2HnJ4/VYqViRoyj4O5DKnyvBxplOk/V+YwBU9/OaMtYYYWd+rsc7fUhxV5oiAYEd+Q=
